version: '3.8'

services:
  hrm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    volumes:
      - .env:/app/.env
