version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${PROD_MONGO_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEV_MODE=${DEV_MODE}
      - COMPANY_UPLOAD_PRESET=${COMPANY_UPLOAD_PRESET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_IMAGE_ACCCESS_PATH=${CLOUDINARY_IMAGE_ACCCESS_PATH}
